config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  get 'home/supplies'
  root 'home#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.primary_key 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def supplies
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/_footer.html.erb
  <footer class="footer">
  	 <div class="container">
  	 	<div class="row">
  	 		<div class="footer-col">
  	 			<h4> A Escola</h4>
  	 			<ul>
  	 				<li><a href="#">Sobre</a></li>
  	 				<li><a href="#">Nossos Serviços</a></li>
  	 				<li><a href="#">Política de privacidade</a></li>
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>Ajuda</h4>
  	 			<ul>
  	 				<li><a href="#">FAQ</a></li>
  	 				<li><a href="#">Opções de pagamento</a></li>
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>Loja</h4>
  	 			<ul>
  	 				<li><a href="#">Casaco</a></li>
  	 				<li><a href="#">Materias</a></li>
  	 				<li><a href="#">Fardamento</a></li>
  	 			</ul>
  	 		</div>
  	 		<div class="footer-col">
  	 			<h4>Acompanhe a gente</h4>
  	 			<div class="social-links">
  	 				<a href="https://www.facebook.com/esfaoficial"><i class="fab fa-facebook-f"></i></a>
  	 				<a href="https://www.instagram.com/esfasobralce/"><i class="fab fa-instagram"></i></a>
  	 				<a href="#"><i class="fab fa-youtube"></i></a>
  	 			</div>
  	 		</div>
  	 	</div>
  	 </div>
  </footer>

app/views/home/_header.html.erb
<header1>

      <nav class="nav-bar1">
            
            <div style="text-align: left">
                    <ul>
                        <li>
                            <%= link_to "Lista de materias 2024", home_supplies_path, class:"nav-link", style:"font-weight: bold; color: #fefefe; text-decoration: underline;"%>
                        <li>
                            <a style="color: #fefefe;">3611-1254</a>
                        </li>
                        <li>
                            <a style="color: #fefefe;">fale@esfanet.com.br</a>                    
                        </li>
                    </ul>
            </div>   
                  
      </nav>
      <div style="text-align: right;">
         <a href="https://www.facebook.com/esfaoficial"><i class="fab fa-facebook-f"></i></a>
         <a href="https://www.instagram.com/esfasobralce/"><i class="fab fa-instagram"></i></a>
         <a href="#"><i class="fab fa-youtube"></i></a>
      </div>  
</header1>

<div class="parent">
      <div>
          <%= image_tag('logos/logo3.png', alt: 'Description', style: 'display: block; margin: 20px; margin-left: 150px; width: 200px; padding: 15px;')%>
      </div>
      <div>
       <a href="https://saseducacao.com.br/" > <%= image_tag('logos/sas.png', alt: 'Description', style: 'display: block; margin: 20px; width: 200px; padding: 15px;')%> </a>
      </div>
      <div>
       <a href="https://siga.activesoft.com.br/login/" > <%= image_tag('logos/activesoft.png', alt: 'Description', style: 'display: block; margin-top: 50px; width: 230px; padding: 5px;')%> </a>
      </div>
      <div>
        <form class="d-flex" role="search">
          <input  type="search" placeholder="O que procura?" >
          <button class="button" type="submit" >Buscar</button>
        </form>
      </div>
</div>

  <header>
          <div class="logo">
            <a>
                ESFA
            </a>
          </div>
          <div class="hamburguer">
              <div class="line"></div>
              <div class="line"></div>
              <div class="line"></div>
          </div>
          <nav class="nav-bar">
              <ul>
                  <li>
                      <a href="#" class="active">Início</a>
                  </li>
                  <li class="nav-item">
                      <%= link_to "A Escola", home_about_path, class:"nav-link" %>
                  </li>
                  <li>
                      <a href="" >Fundamental I</a>
                  </li>
                  <li>
                      <a href="" >Fundamental II</a>
                  </li>
                  <li>
                      <a href="" >SAS</a>
                  </li>
                  <li>
                      <a href="" >Fotos</a>
                  </li>
                </div>
              </ul>
          </nav>
    </header>

app/views/home/about.erb
<div class="container">
  <%= image_tag('about/fachada_antiga.jpg') %>
  <div class="text-block">
    <h4>Escola São Francisco de Assis</h4>
    <p>Escola São Francisco de Assis</p>
  </div>
</div>

<%= image_tag('logos/logo3.png', alt: 'Description', style: 'display: block; margin: 20px; margin-left: 150px; width: 200px; padding: 15px;')%>

app/views/home/index.html.erb
  <div  id="myCarousel" class="carousel slide" data-bs-ride="carousel" >
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class="active" aria-current="true"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div>
      <div class="carousel-inner">
        <div class="carousel-item">
      
          <%= image_tag("banner/carousel_fachada.png", width: '100%', height: '450px') %>
          
          <div class="container">
            <div class="carousel-caption text-start">
              <h1>MATRICULAS 2024 ABERTAS</h1>
              <p>Escola São Francisco de Assis</p>
              <p><a class="btn btn-lg btn-primary" href="#">PRÉ-MATRÍCULA</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item active">
        <%= image_tag("banner/esfanoar.jpeg", width: '100%', height: '450px')%>
          <div class="container">
            <div class="carousel-caption">
              <h1></h1>
              <p></p>
              <p><a class="btn btn-lg btn-primary" href="#">Acompanhe</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
        <%= image_tag("banner/parceiros.png", width: '100%', height: '450px') %>
          <div class="container">
            <div class="carousel-caption text-end">
              <h1>One more for good measure.</h1>
              <p>Some representative placeholder content for the third slide of this carousel.</p>
              <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
            </div>
          </div>
        </div>
       </div>
      </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">

    <!-- FOTO DO INFANTIL -->    
      <div class="col-lg-4">
      <%= image_tag('logos/infantil.jpeg', class: 'rounded-circle' ,alt: 'Description', style: 'display: block; width: 200px; padding: 15px; margin-top: 30px') %>
        <h2 class="fw-normal">INFANTIL 1</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        <p><a class="btn btn-secondary" href="#">Mais detalhes »</a></p>
      </div><!-- /.col-lg-4 -->

      <!-- FOTO DO FUNDAMENTAL 1 -->
      <div class="col-lg-4">
        <%= image_tag('logos/fund1.jpeg', class: 'rounded-circle', alt: 'Description', style: 'display: block; width: 200px; padding: 15px;margin-top: 30px')%>
          <h2 class="fw-normal">Ensino Fundamental - Anos iniciais</h2>
          <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
          <p><a class="btn btn-secondary" href="#">Mais detalhes »</a></p>
      </div><!-- /.col-lg-4 -->

      <!-- FOTO DO FUNDAMENTAL 2 -->
      <div class="col-lg-4">

      <%= image_tag('logos/fund2.jpeg', class: 'rounded-circle', alt: 'Description', style: 'display: block; width: 200px; padding: 15px;margin-top: 30px')%>
        <h2 class="fw-normal">Ensino Fundamental - Anos Finais</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
        <p><a class="btn btn-secondary" href="#">Mais detalhes »</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">ESFA no Ar. <span class="text-body-secondary"></span></h2>
        <p class="lead">Todos os sábados de 9h às 11h. Na rádio Educadora FM 107,5</p>
      </div>
      <div class="col-md-5">
      <%= image_tag("banner/esfanoar2.jpeg", width: '350', height: '350px') %><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em"></text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">Oh yeah, it’s that good. <span class="text-body-secondary">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">And lastly, this one. <span class="text-body-secondary">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

    <script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>

app/views/home/supplies.erb
<a style: align="center"><h3> Lista de Materias </h3></a>

<ul class="list-group" style: align="center">
  <li class="list-group-item"><a href="https://acrobat.adobe.com/id/urn:aaid:sc:US:19190b55-e12e-4839-8c16-3cc744ad37f8">1º Ano Fundamental I</a></li>
  <li class="list-group-item"><a href="https://acrobat.adobe.com/id/urn:aaid:sc:US:cb81070e-f357-4d4e-aaa4-4c1368c2be5b">2º Ano Fundamental I</a></li>
  <li class="list-group-item"><a href="https://acrobat.adobe.com/id/urn:aaid:sc:US:b463dc01-460a-4559-9d0a-ed745bbc5fbe">3º Ano Fundamental I</a></li>
  <li class="list-group-item"><a href="https://acrobat.adobe.com/id/urn:aaid:sc:US:3699a6fc-a14c-4fc8-b5bb-0b0ec0792126">4º Ano Fundamental I</a></li>
  <li class="list-group-item"><a href="https://acrobat.adobe.com/id/urn:aaid:sc:US:84119141-baec-4902-9531-89ac0e3b33a2">5º Ano Fundamental I</a></li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="br">
  <head>


    <!-- Required meta tags -->
    <link rel="icon" type="image/png" href="/assets/logo3.png">

    <meta charset="UTF-8"
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-widith, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Bootstrap CSS -->


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

    <title>ESFA</title>
  </head>
  <body>
    <%= render 'home/header' %>
      <%= yield %>
      <%= render 'home/footer' %>
    </div>
    


    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>